name: "Build release"
on:
  push:
    tags:
      - v0.0.0
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x ./scripts/mkdkmsconf.sh

      - name: Run build script
        run: |
          bash ./scripts/mkdkmsconf.sh  # 确保脚本用 bash 执行
          make dkms-tarball
          mkdir -p build/
          mv dkms.tar.gz build/tcp-brutal.dkms.tar.gz

      - name: List files
        run: ls -la

      - name: Generate hashes
        run: |
          for file in build/*; do
            sha256sum $file >> build/hashes.txt
          done

      - name: Upload GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
